### ISSUE TITLE
Add option to group types (classes/enums etc)

### ISSUE THREAD

**Issue by andy0x10** [Jan0660/DocFxMarkdownGen#6]
Super handy tool!

This one is probably out of scope but I thought I'd ask..

It would be a really useful to have an option to generate grouping (folders) for different types.  This way all of the classes would be together and all of the enums would be together.

**Comment by Jan0660** [comment]
Released [v0.3.0](https://github.com/Jan0660/DocFxMarkdownGen/releases/tag/v0.3.0) with this and updated README.
If you were using `dfmg-template2` you need to update to the new `generate.sh` for the config settings to apply when building versions.
